### ISSUE TITLE
Flatpak version can not be used with `--update` / can't write updates to manifest

### ISSUE THREAD

**Issue by dreua** [flathub/org.flathub.flatpak-external-data-checker#117]
Using `--update` with the flatpak version results in a `OSError: [Errno 30] Read-only file system` because the file system access is granted as read only. 

- [ ] https://github.com/flathub/org.flathub.flatpak-external-data-checker/pull/223

**Comment by tinywrkb** [comment]
>Can this be added to the Readme / documentation to make it easier for new users?

Done in flathub/flatpak-external-data-checker#320.

**Comment by wjt** [comment]
Let's leave this ticket open for the other proposal made on that PR, namely to give a more helpful error message

**Comment by bbhtt** [comment]
This is a development/packaging tool, why not just give it rw host (or home) like flatpaked flatpak-builder? https://github.com/flathub/org.flatpak.Builder/blob/1a4713682b0761e289f5e1b87f84de033920a61c/org.flatpak.Builder.json#L13

**Comment by dreua** [comment]
A better error message would be my preferred option. Ideally it would have write access to the current working directory or the file given as argument but that might be not possible. Think of a file portal just on the CLI ;)

**Comment by bbhtt** [comment]
A file might not be writeable for multiple reasons - it doesn't have to be only, read-only, to cause writing changes to fail. It'd get messy to catch each such error and print an error message for the sandboxed and non-sandboxed cases. There's no one instruction to put in the error message to make it more helpful that can work for all.

It's a good idea I think to let the inbuilt error codes show up.

**Comment by dreua** [comment]
Yes I think a hint for the most common mistake would be valuable anyway. 

> It's a good idea I think to let the inbuilt error codes show up.

Yes, absolutely! The idea is to just add hrplful information to it, not make it disappear. You could just "raise" the original error after printing something if I'm not mistaken.

**Comment by dreua** [comment]
Thank you for taking care of that, @bbhtt and @wjt !
